# Generated by Django 5.0.6 on 2024-07-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('burgers', models.JSONField(null=True)),
                ('pizzas', models.JSONField(null=True)),
                ('pastas', models.JSONField(null=True)),
                ('fries', models.JSONField(null=True)),
                ('drinks', models.JSONField(null=True)),
                ('delivery', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=2000, null=True)),
                ('order_complete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=14)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('number_of_people', models.IntegerField()),
                ('table_number', models.IntegerField()),
            ],
        ),
    ]
