# Generated by Django 5.0.6 on 2024-07-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inventory_orders_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='drinks',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='fries',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='pastas',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='pizzas',
        ),
    ]
