# Generated by Django 5.0.6 on 2024-07-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_orders_drinks_remove_orders_fries_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='burgers',
            new_name='items',
        ),
    ]
